AWSTemplateFormatVersion: 2010-09-09
Description: WrapperTemplate
Resources:
  WrappedStackWithStackLevelTags:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Tags:
        - Key: Environment
          Value: Test
        - Key: Project
          Value: Demo
      TemplateURL: 'https://s3.amazonaws.com/ecs-refarch-cloudformation/master.yaml'

Parameters:
  EnvironmentType:
    Description: Environment type.
    Default: Test
    Type: String
    AllowedValues:
      - Production
      - Staging
      - Test
    ConstraintDescription: 'You must specify Test, Staging, or Production.'

Conditions:
  CreateProductionResources: !Equals 
    - !Ref EnvironmentType
    - Production
  CreateStagingResources: !Equals 
    - !Ref EnvironmentType
    - Staging
  CreateTestResources: !Equals 
    - !Ref EnvironmentType
    - Test
