Description: >
    This template deploys an Application Load Balancer that exposes our various ECS services.
    We create them it a seperate nested template, so it can be referenced by all of the other nested templates.

Parameters:

    RessourcePrefix:
        Description: An ressources name prefix that will be prefixed to resource names
        Type: String

    EnvironmentType:
        Description: "Definition of the Environment type: Test, Staging or Production."
        Default: Test
        Type: String
        AllowedValues:
          - Production
          - Staging
          - Test
        ConstraintDescription: "You must specify Test, Staging, or Production."

    ProjectName:
        Description: Short name of project this stack is used in/for.
        Default: Project Name
        Type: String
        MinLength: 2
        MaxLength: 15
        AllowedPattern: "[A-Za-z0-9][-. A-Za-z0-9]*"
        ConstraintDescription: Must be between 2 and 15 characters long and may contain alphanumeric characters, hyphens (-), and dots (.), but must start with alphanumeric.

    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the Application Load Balancer should be deployed to

    Subnets:
        Description: Choose which subnets the Application Load Balancer should be deployed to
        Type: List<AWS::EC2::Subnet::Id>

    SecurityGroup:
        Description: Select the Security Group to apply to the Application Load Balancer
        Type: AWS::EC2::SecurityGroup::Id

Resources:

    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Name: !Ref RessourcePrefix
            Subnets: !Ref Subnets
            SecurityGroups: 
                - !Ref SecurityGroup
            Tags:
                - Key: Name
                  Value: !Sub ${RessourcePrefix} ECS ALBv2
                - Key: Environment
                  Value: !Ref EnvironmentType
                - Key: Project
                  Value: !Ref ProjectName

    LoadBalancerListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref LoadBalancer
            Port: 80
            Protocol: HTTP 
            DefaultActions: 
                - Type: forward
                  TargetGroupArn: !Ref DefaultTargetGroup
    
    # We define a default target group here, as this is a mandatory Parameters
    # when creating an Application Load Balancer Listener. This is not used, instead
    # a target group is created per-service in each service template (../services/*)
    DefaultTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Sub ${RessourcePrefix}-default
            VpcId: !Ref VPC
            Port: 80
            Protocol: HTTP
            Tags: 
                - Key: Environment
                  Value: !Ref EnvironmentType
                - Key: Project
                  Value: !Ref ProjectName
           
Outputs:

    LoadBalancer:
        Description: A reference to the Application Load Balancer
        Value: !Ref LoadBalancer

    LoadBalancerUrl:
        Description: The URL of the ALB
        Value: !GetAtt LoadBalancer.DNSName

    Listener:
        Description: A reference to a port 80 listener
        Value: !Ref LoadBalancerListener  

    
